project_id = "ymqrbxiqtadliydzqldj"

[functions.create-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.get-download-url]
verify_jwt = false

[functions.send-vault-created]
verify_jwt = true

[functions.get-owner-branding]
verify_jwt = false

[functions.resend-vault-email]
verify_jwt = true

[functions.asaas-checkout]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.cleanup-expired-vaults]
verify_jwt = false

[functions.log-vault-event]
verify_jwt = false

[functions.mp-oauth-callback]
verify_jwt = false

